import { IProduct } from "./types";

export const productList: IProduct[] = [
  {
    id: "NJ2317-E-XL-TVP2-QP51-C4",
    name: "NJ2317-E-XL-TVP2-QP51-C4",
    price: "по запросу",
    inD: "50",
    wD: "150",
    h: "65",
    m: "0.084",
    brand: "FAG",
    img: "double-row.jpg",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "FAG" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "6-2007117 A",
    name: "6-2007117 A",
    price: "50",
    inD: "5",
    wD: "70/500",
    h: "70/50",
    m: "0.84",
    brand: "SKF",
    img: "roller-bearings.jpg",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "32130Д",
    name: "32130Д",
    price: "150",
    inD: "10",
    wD: "900/700",
    h: "70/500",
    m: "8.04",
    brand: "Timken",
    img: "persistent.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "23030 CC/W33 FBC",
    name: "23030 CC/W33 FBC",
    price: "2700",
    inD: "100",
    wD: "35,765",
    h: "900/700",
    m: "18.04",
    brand: "NSK",
    img: "single-row.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "UCF 207",
    name: "UCF 207",
    price: "31000",
    inD: "70/50",
    wD: "50",
    h: "35,765",
    m: "118.04",
    brand: "Koya",
    img: "spherical.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "205",
    name: "205",
    price: "165200",
    inD: "70/500",
    wD: "75",
    h: "50",
    m: "1500.04",
    brand: "NTN / NSR",
    img: "housing-units.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "36-232726Е2М",
    name: "36-232726Е2М",
    price: "2053893",
    inD: "900/700",
    wD: "5",
    h: "75",
    m: "8.04",
    brand: "Craft",
    img: "needle-shaped.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "6307",
    name: "6307",
    price: "2700,52",
    inD: "35,765",
    wD: "10",
    h: "5",
    m: "8.04",
    brand: "ГПЗ 10",
    img: "conical.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "3530 Л ",
    name: "3530 Л ",
    price: "2053893,54",
    inD: "50",
    wD: "100",
    h: "10",
    m: "8.04",
    brand: "Nachi",
    img: "articulated.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
  {
    id: "180316",
    name: "TKVD25WG3HJ680202INA",
    price: "132",
    inD: "75",
    wD: "70/50",
    h: "100",
    m: "8.04",
    brand: "INA",
    img: "ball-bearings.png",
    images: ["double-row.jpg", "roller-bearings.jpg", "persistent.png"],
    article: "П0000034648",
    specifications: [
      { name: "Диаметр внутренний (d), мм", value: "10" },
      { name: "Диаметр внешний (D), мм", value: "30" },
      { name: "Ширина (В), мм", value: "9" },
      { name: "Вес [кг]", value: "0,032" },
      { name: "Бренд", value: "АФП" },
      {
        name: "Уплотнение (расшифровка)",
        value: "2RS (двустороннее резиновое уплотнение)",
      },
      { name: "Материал", value: "Сталь" },
      { name: "Зазор", value: "CN (нормальный зазор)" },
      { name: "Сепаратор", value: "Сталь" },
      { name: "Статическая нагрузка C0, Н", value: "224" },
      { name: "Динамическая нагрузка C, Н", value: "5300" },
      { name: "Класс точности", value: "P6" },
      { name: "Диапазон температур", value: "от -40° до +100°" },
      { name: "Тип отверстия", value: "Цилиндрическое" },
      { name: "Рядность подшипника", value: "Однорядный" },
    ],
  },
];
