import { ICategory } from "../model/types";

export const categoryList: ICategory[] = [
  {
    id: "ball-bearings",
    name: "Шариковые",
    images: "ball-bearings.png",
    productsCount: 12500,
    url: "/products/ball-bearings",
  },
  {
    id: "roller-bearings",
    name: "Роликовые",
    images: "roller-bearings.png",
    productsCount: 15500,
    url: "/products/roller-bearings",
  },
  {
    id: "needle-shaped",
    name: "Игольчатые",
    images: "needle-shaped.png",
    productsCount: 15500,
    url: "/products/needle-shaped",
  },
  {
    id: "spherical",
    name: "Сферические",
    images: "spherical.png",
    productsCount: 15500,
    url: "/products/spherical",
  },
  {
    id: "conical",
    name: "Конические",
    images: "conical.png",
    productsCount: 15500,
    url: "/products/ball-bearings",
  },
  {
    id: "single-row",
    name: "Однорядные",
    images: "single-row.png",
    productsCount: 15500,
    url: "/products/single-row",
  },
  {
    id: "double-row",
    name: "Двухрядные",
    images: "double-row.png",
    productsCount: 15500,
    url: "/products/double-row",
  },
  {
    id: "housing-units",
    name: "Корпусные узлы",
    images: "housing-units.png",
    productsCount: 15500,
    url: "/products/housing-units",
  },
  {
    id: "articulated",
    name: "Шарнирные",
    images: "articulated.png",
    productsCount: 15500,
    url: "/products/articulated",
  },
  {
    id: "persistent",
    name: "Упорные",
    images: "persistent.png",
    productsCount: 15500,
    url: "/products/persistent",
  },
  {
    id: "automotive",
    name: "Автомобильные",
    images: "automotive.png",
    productsCount: 15500,
    url: "/products/automotive",
  },
  {
    id: "catalog",
    name: "В каталог",
    images: "catalog.png",
    productsCount: 15500,
    url: "/products",
  },
];
