import { IBrand } from "../model/types";

export const brandsList: IBrand[] = [
  {
    id: "skf",
    name: "SKF",
    images: "skf-logo.png",
    productsCount: 12500,
    url: "/catalog/skf",
  },
  {
    id: "nsk",
    name: "NSK",
    images: "nsk-logo.png",
    productsCount: 12500,
    url: "/catalog/nsk",
  },
  {
    id: "fag",
    name: "FAG",
    images: "fag-logo.png",
    productsCount: 12500,
    url: "/catalog/fag",
  },
  {
    id: "koyo",
    name: "KOYO",
    images: "koyo-logo.png",
    productsCount: 12500,
    url: "/catalog/koyo",
  },
  {
    id: "snr",
    name: "SNR",
    images: "snr-logo.png",
    productsCount: 12500,
    url: "/catalog/snr",
  },
  {
    id: "ntn",
    name: "NTN",
    images: "ntn-logo.png",
    productsCount: 12500,
    url: "/catalog/ntn",
  },
  {
    id: "bosch",
    name: "BOSCH",
    images: "bosch-logo.png",
    productsCount: 12500,
    url: "/catalog/bosch",
  },
  {
    id: "ina",
    name: "INA",
    images: "craft-logo.png",
    // images: "ina-logo.png",
    productsCount: 12500,
    url: "/catalog/ina",
  },
  {
    id: "timken",
    name: "TIMKEN",
    images: "timken-logo.png",
    productsCount: 12500,
    url: "/catalog/timken",
  },
  {
    id: "craft",
    name: "Craft",
    images: "craft-logo.png",
    productsCount: 12500,
    url: "/catalog/craft",
  },
  {
    id: "mpz",
    name: "МПЗ",
    images: "mpz-logo.png",
    productsCount: 12500,
    url: "/catalog/mpz",
  },
  {
    id: "nachi",
    name: "Nachi",
    images: "nachi-logo.png",
    productsCount: 12500,
    url: "/catalog/nachi",
  },
];
